# Generated by Django 4.0.3 on 2022-04-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0002_usermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
    ]
