# Generated by Django 4.0.3 on 2022-04-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book_app', '0005_alter_contactdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_book_app.user'),
        ),
    ]
